Iter5
BrownBear56/contractor pull request #5
Opened 2024-12-02 06:54 UTC by BrownBear56

2024-12-06 12:03 UTC, BrownBear56 commented on cmd/client/main.go
Окей, сам пользуюсь postman. Но зачем-то в курсе было сказано, что лучше добавить клиент себе в проект. Это сбивает с толку

2024-12-08 22:32 UTC, s-shpak requested changes

2024-12-08 22:32 UTC, s-shpak commented on cmd/shortener/config/config.go
> +	addressEnv, addressExists := os.LookupEnv("SERVER_ADDRESS")
Если функция в Go возвращает вторую переменную булевого типа, которая указывает на корректность выполнения операции и т.п., ее принято называть `ok`.

2024-12-08 22:32 UTC, s-shpak commented on cmd/shortener/handlers/handlers.go
> +		if _, exists := storage.get(id); !exists {
Что если проверка завершилась успешно, но до того, как ты добавил новую коротку ссылку в хранилище, другая горутина добавит ее же (случайно сгенерирует такое же значение)? Подумай, как это исправить

2024-12-08 22:32 UTC, s-shpak commented on cmd/shortener/handlers/handlers.go
> +	for {
Мы рискуем никогда не выйти из этого цикла. Это возможно, если:
1. свободные 6-значные значения уже исчерпаны
2. в логике генерации есть баг

Логичнее было бы попробовать сгенерировать короткую ссылку `n` раз, после чего вернуть ошибку пользователю, если это не получилось

2024-12-08 22:32 UTC, s-shpak commented on cmd/shortener/handlers/handlers_test.go
> +			assert.Equal(t, tt.expectedStatus, resp.Result().StatusCode, "unexpected status code")
Этот false positive можно явным образом проигнорировать: https://golangci-lint.run/usage/false-positives/

2024-12-08 22:33 UTC, s-shpak requested changes
Также поправь проблемы, задетекченные Github Actions

2024-12-09 13:16 UTC, s-shpak requested changes
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`.

2024-12-10 14:12 UTC, BrownBear56 commented on cmd/shortener/handlers/handlers.go
> +		if _, exists := s.urlStore[id]; !exists {
А разве в начале метода  generateAndSaveID	s.mu.Lock() defer s.mu.Unlock() не должен заблокировать целиком все операции в рамках метода?

2024-12-11 10:16 UTC, s-shpak requested changes

2024-12-11 10:16 UTC, s-shpak commented on cmd/shortener/handlers/handlers.go
> +		if _, exists := s.urlStore[id]; !exists {
Должен. Прошу прощения, не увидел взятие мьютекса.

Вообще, я бы советовал тебе не вызывать генерацию ссылки в мьютексе: мьютекс должен захватываться на как можно более короткий период. Кроме того, кажется, что генерация ссылки -- ответственность не хранилища, а бизнес-логики.

Потому рекомендую вынести генерацию выше, а в этом методе только проверять значение на повторяющееся, и сохранять его, если это не так

2024-12-12 19:10 UTC, s-shpak approved these changes

2024-12-13 09:56 UTC, merged